import Link from "next/link";
import { ArrowRight, Clock3, TriangleAlert } from "lucide-react";
import { MetricCard } from "@/components/metric-card";
import { PageHeader } from "@/components/page-header";
import { LeadScore } from "@/components/lead-score";
import { StatusBadge } from "@/components/status-badge";
import { DateLabel } from "@/components/date-label";
import { getDashboardSummary } from "@/lib/services/dashboard";
import { PIPELINE_GROUPS } from "@/lib/domain/status";

export default async function OverviewPage() {
  const data = await getDashboardSummary();
  return <><PageHeader title="Overview" description="O que precisa avançar agora no pipeline."/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><MetricCard label="Leads ativos" value={data.activeLeads}/><MetricCard label="Ações vencidas" value={data.overdueActions}/><MetricCard label="Contato hoje" value={data.contactToday}/><MetricCard label="Propostas abertas" value={data.openProposals}/><MetricCard label="Negociação" value={data.negotiation}/><MetricCard label="Ganhos" value={data.won}/></div>
  <div className="mt-6 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><section className="surface-flat rounded-lg"><div className="flex items-center justify-between border-b border-default px-4 py-3"><div><h2 className="text-sm font-semibold">Needs attention</h2><p className="text-xs text-muted">Atrasos, ausência de próxima ação e leads prioritários.</p></div><Link href="/actions" className="flex items-center gap-1 text-xs text-muted hover:text-[var(--text)]">Ver tudo <ArrowRight size={13}/></Link></div><div className="divide-y divide-[var(--border)]">{data.needsAttention.map((lead) => <Link href={`/leads/${lead.id}`} key={lead.id} className="grid gap-3 px-4 py-3 hover:bg-[var(--panel-2)] sm:grid-cols-[1fr_auto_auto]"><div><div className="flex items-center gap-2"><span className="text-sm font-medium">{lead.name}</span>{!lead.nextAction ? <TriangleAlert size={13} className="text-amber-600"/> : null}</div><p className="mt-1 text-xs text-muted">{lead.nextAction ?? "Sem próxima ação definida"}</p></div><div className="flex items-center gap-2"><LeadScore score={lead.score}/><StatusBadge status={lead.status}/></div><div className="flex items-center gap-1"><Clock3 size={12} className="text-muted"/><DateLabel value={lead.nextActionAt} highlightOverdue/></div></Link>)}</div></section>
  <section className="surface-flat rounded-lg"><div className="border-b border-default px-4 py-3"><h2 className="text-sm font-semibold">Pipeline snapshot</h2><p className="text-xs text-muted">Distribuição pelos grupos operacionais.</p></div><div className="space-y-4 p-4">{PIPELINE_GROUPS.map((group) => { const count = group.statuses.reduce((sum, status) => sum + (data.countsByStatus[status] ?? 0), 0); const pct = data.activeLeads ? Math.min(100, Math.round((count / data.activeLeads) * 100)) : 0; return <div key={group.id}><div className="mb-1 flex justify-between text-xs"><span>{group.label}</span><span className="font-mono text-muted">{count}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-[var(--panel-2)]"><div className="h-full rounded-full bg-[var(--text)] opacity-75" style={{ width: `${pct}%` }}/></div></div>; })}</div></section></div></>;
}
