import { boolean, check, index, integer, jsonb, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import type { ActivityType, ActorType, LeadStatus, LeadTaskPriority, LeadTaskStatus, LeadTaskType, ServiceOpportunity, UserRole } from "@/lib/domain/types";
import type { AiRunStatus, ApprovalActionType, ApprovalStatus, ClientProjectStatus, ContractStatus, DiagnosticFinding, DiagnosticRecommendation, DiagnosticStatus, ObligationStatus, PolicyCheck, ProfileFact, ProposalStatus } from "@/lib/domain/automation";

export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  role: text("role").$type<UserRole>().notNull().default("MEMBER"),
  passwordHash: text("password_hash"),
  active: boolean("active").notNull().default(true),
  lastLoginAt: timestamp("last_login_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const userSessions = pgTable("user_sessions", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  tokenHash: text("token_hash").notNull().unique(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull().defaultNow(),
  revokedAt: timestamp("revoked_at", { withTimezone: true }),
}, (table) => [
  index("user_sessions_user_idx").on(table.userId),
  index("user_sessions_expires_idx").on(table.expiresAt),
  index("user_sessions_revoked_idx").on(table.revokedAt),
]);

export const mcpCredentials = pgTable("mcp_credentials", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  tokenHash: text("token_hash").notNull().unique(),
  tokenPrefix: text("token_prefix").notNull(),
  scopes: jsonb("scopes").$type<string[]>().notNull().default(["leads.read", "leads.write"]),
  active: boolean("active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  lastUsedAt: timestamp("last_used_at", { withTimezone: true }),
  revokedAt: timestamp("revoked_at", { withTimezone: true }),
  expiresAt: timestamp("expires_at", { withTimezone: true }),
}, (table) => [
  index("mcp_credentials_user_idx").on(table.userId),
  index("mcp_credentials_active_idx").on(table.active),
  index("mcp_credentials_revoked_idx").on(table.revokedAt),
  index("mcp_credentials_expires_idx").on(table.expiresAt),
]);

export const leads = pgTable(
  "leads",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    name: text("name").notNull(),
    legalName: text("legal_name"),
    segment: text("segment"),
    city: text("city"),
    state: text("state"),
    website: text("website"),
    googleMapsUrl: text("google_maps_url"),
    instagramUrl: text("instagram_url"),
    phone: text("phone"),
    whatsapp: text("whatsapp"),
    email: text("email"),
    contactName: text("contact_name"),
    contactRole: text("contact_role"),
    status: text("status").$type<LeadStatus>().notNull().default("DISCOVERED"),
    score: integer("score"),
    scoreReasons: jsonb("score_reasons").$type<string[]>().notNull().default([]),
    primaryOpportunity: text("primary_opportunity").$type<ServiceOpportunity>(),
    opportunityNotes: text("opportunity_notes"),
    ownerId: uuid("owner_id").references(() => users.id, { onDelete: "set null" }),
    tags: jsonb("tags").$type<string[]>().notNull().default([]),
    sourceType: text("source_type"),
    sourceUrl: text("source_url"),
    nextAction: text("next_action"),
    nextActionAt: timestamp("next_action_at", { withTimezone: true }),
    nextActionOwnerId: uuid("next_action_owner_id").references(() => users.id, { onDelete: "set null" }),
    doNotContact: boolean("do_not_contact").notNull().default(false),
    version: integer("version").notNull().default(1),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("leads_status_idx").on(table.status),
    index("leads_score_idx").on(table.score),
    index("leads_city_idx").on(table.city),
    index("leads_next_action_at_idx").on(table.nextActionAt),
    index("leads_updated_at_idx").on(table.updatedAt),
  ],
);

export const leadActivities = pgTable(
  "lead_activities",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    leadId: uuid("lead_id").notNull().references(() => leads.id, { onDelete: "cascade" }),
    type: text("type").$type<ActivityType>().notNull(),
    actorType: text("actor_type").$type<ActorType>().notNull(),
    actorId: text("actor_id").notNull(),
    actorName: text("actor_name").notNull(),
    summary: text("summary").notNull(),
    metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("lead_activities_lead_idx").on(table.leadId), index("lead_activities_created_idx").on(table.createdAt)],
);

export const leadEvidence = pgTable(
  "lead_evidence",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    leadId: uuid("lead_id").notNull().references(() => leads.id, { onDelete: "cascade" }),
    sourceUrl: text("source_url").notNull(),
    sourceType: text("source_type"),
    observedAt: timestamp("observed_at", { withTimezone: true }),
    claim: text("claim").notNull(),
    value: text("value").notNull(),
    confidence: integer("confidence"),
    createdBy: text("created_by").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("lead_evidence_lead_idx").on(table.leadId)],
);

export const auditLogs = pgTable(
  "audit_logs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    actorType: text("actor_type").$type<ActorType>().notNull(),
    actorId: text("actor_id").notNull(),
    tool: text("tool"),
    action: text("action").notNull(),
    leadId: uuid("lead_id").references(() => leads.id, { onDelete: "set null" }),
    entityType: text("entity_type"),
    entityId: text("entity_id"),
    input: jsonb("input").$type<Record<string, unknown>>().notNull().default({}),
    result: jsonb("result").$type<Record<string, unknown>>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("audit_logs_lead_idx").on(table.leadId), index("audit_logs_entity_idx").on(table.entityType, table.entityId), index("audit_logs_created_idx").on(table.createdAt)],
);

export const leadTasks = pgTable(
  "lead_tasks",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    leadId: uuid("lead_id").notNull().references(() => leads.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    description: text("description"),
    type: text("type").$type<LeadTaskType>().notNull().default("TASK"),
    status: text("status").$type<LeadTaskStatus>().notNull().default("TODO"),
    priority: text("priority").$type<LeadTaskPriority>().notNull().default("MEDIUM"),
    dueAt: timestamp("due_at", { withTimezone: true }),
    startAt: timestamp("start_at", { withTimezone: true }),
    endAt: timestamp("end_at", { withTimezone: true }),
    allDay: boolean("all_day").notNull().default(false),
    ownerId: uuid("owner_id").references(() => users.id, { onDelete: "set null" }),
    sortOrder: integer("sort_order").notNull().default(0),
    createdByType: text("created_by_type").$type<ActorType>().notNull(),
    createdById: text("created_by_id"),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    canceledAt: timestamp("canceled_at", { withTimezone: true }),
    version: integer("version").notNull().default(1),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("lead_tasks_lead_idx").on(table.leadId),
    index("lead_tasks_status_idx").on(table.status),
    index("lead_tasks_owner_idx").on(table.ownerId),
    index("lead_tasks_due_idx").on(table.dueAt),
    index("lead_tasks_start_idx").on(table.startAt),
    index("lead_tasks_end_idx").on(table.endAt),
    index("lead_tasks_owner_status_due_idx").on(table.ownerId, table.status, table.dueAt),
    index("lead_tasks_lead_status_idx").on(table.leadId, table.status),
    check("lead_tasks_event_pair", sql`(${table.startAt} IS NULL) = (${table.endAt} IS NULL)`),
    check("lead_tasks_event_order", sql`${table.endAt} IS NULL OR ${table.endAt} >= ${table.startAt}`),
    check("lead_tasks_done_completed", sql`${table.status} <> 'DONE' OR ${table.completedAt} IS NOT NULL`),
    check("lead_tasks_canceled_at", sql`${table.status} <> 'CANCELED' OR ${table.canceledAt} IS NOT NULL`),
  ],
);


export const businessProfiles = pgTable("business_profiles", {
  id: uuid("id").primaryKey().defaultRandom(),
  leadId: uuid("lead_id").notNull().references(() => leads.id, { onDelete: "cascade" }),
  version: integer("version").notNull().default(1),
  identity: jsonb("identity").$type<Record<string, unknown>>().notNull().default({}),
  contacts: jsonb("contacts").$type<Record<string, unknown>>().notNull().default({}),
  businessSignals: jsonb("business_signals").$type<Record<string, unknown>>().notNull().default({}),
  competition: jsonb("competition").$type<Record<string, unknown>[]>().notNull().default([]),
  facts: jsonb("facts").$type<ProfileFact[]>().notNull().default([]),
  createdByType: text("created_by_type").$type<ActorType>().notNull(),
  createdById: text("created_by_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index("business_profiles_lead_idx").on(t.leadId), index("business_profiles_lead_version_idx").on(t.leadId, t.version)]);

export const diagnostics = pgTable("diagnostics", {
  id: uuid("id").primaryKey().defaultRandom(),
  leadId: uuid("lead_id").notNull().references(() => leads.id, { onDelete: "cascade" }),
  businessProfileId: uuid("business_profile_id").references(() => businessProfiles.id, { onDelete: "set null" }),
  status: text("status").$type<DiagnosticStatus>().notNull().default("DRAFT"),
  version: integer("version").notNull().default(1),
  executiveSummary: text("executive_summary").notNull().default(""),
  strengths: jsonb("strengths").$type<DiagnosticFinding[]>().notNull().default([]),
  gaps: jsonb("gaps").$type<DiagnosticFinding[]>().notNull().default([]),
  recommendations: jsonb("recommendations").$type<DiagnosticRecommendation[]>().notNull().default([]),
  scores: jsonb("scores").$type<Record<string, number>>().notNull().default({}),
  recommendedServices: jsonb("recommended_services").$type<string[]>().notNull().default([]),
  internalNotes: text("internal_notes"),
  publicSummary: text("public_summary"),
  artifactRef: text("artifact_ref"),
  renderedContent: text("rendered_content"),
  generatedByType: text("generated_by_type").$type<ActorType>().notNull(),
  generatedById: text("generated_by_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index("diagnostics_lead_idx").on(t.leadId), index("diagnostics_status_idx").on(t.status), index("diagnostics_updated_idx").on(t.updatedAt)]);

export const scoreAssessments = pgTable("score_assessments", {
  id: uuid("id").primaryKey().defaultRandom(),
  leadId: uuid("lead_id").notNull().references(() => leads.id, { onDelete: "cascade" }),
  diagnosticId: uuid("diagnostic_id").references(() => diagnostics.id, { onDelete: "set null" }),
  digitalGap: integer("digital_gap").notNull(),
  economicPotential: integer("economic_potential").notNull(),
  contactability: integer("contactability").notNull(),
  urgency: integer("urgency").notNull(),
  serviceFit: integer("service_fit").notNull(),
  proofPotential: integer("proof_potential").notNull(),
  total: integer("total").notNull(),
  confidence: integer("confidence").notNull(),
  reasons: jsonb("reasons").$type<string[]>().notNull().default([]),
  recommendedService: text("recommended_service"),
  createdByType: text("created_by_type").$type<ActorType>().notNull(),
  createdById: text("created_by_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index("score_assessments_lead_idx").on(t.leadId), index("score_assessments_created_idx").on(t.createdAt)]);

export const aiRuns = pgTable("ai_runs", {
  id: uuid("id").primaryKey().defaultRandom(),
  skill: text("skill").notNull(),
  skillVersion: text("skill_version").notNull(),
  leadId: uuid("lead_id").references(() => leads.id, { onDelete: "set null" }),
  status: text("status").$type<AiRunStatus>().notNull().default("QUEUED"),
  actorType: text("actor_type").$type<ActorType>().notNull(),
  actorId: text("actor_id").notNull(),
  idempotencyKey: text("idempotency_key"),
  inputSummary: jsonb("input_summary").$type<Record<string, unknown>>().notNull().default({}),
  outputSummary: jsonb("output_summary").$type<Record<string, unknown>>().notNull().default({}),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  startedAt: timestamp("started_at", { withTimezone: true }),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index("ai_runs_skill_idx").on(t.skill), index("ai_runs_lead_idx").on(t.leadId), index("ai_runs_status_idx").on(t.status)]);

export const prospectingRuns = pgTable("prospecting_runs", {
  id: uuid("id").primaryKey().defaultRandom(),
  objective: text("objective").notNull(),
  icp: jsonb("icp").$type<Record<string, unknown>>().notNull().default({}),
  region: text("region"),
  segments: jsonb("segments").$type<string[]>().notNull().default([]),
  sources: jsonb("sources").$type<string[]>().notNull().default([]),
  maxCandidates: integer("max_candidates").notNull().default(50),
  status: text("status").notNull().default("DRAFT"),
  aiRunId: uuid("ai_run_id").references(() => aiRuns.id, { onDelete: "set null" }),
  counters: jsonb("counters").$type<Record<string, number>>().notNull().default({ found: 0, imported: 0, duplicates: 0, rejected: 0 }),
  createdByType: text("created_by_type").$type<ActorType>().notNull(),
  createdById: text("created_by_id").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index("prospecting_runs_status_idx").on(t.status), index("prospecting_runs_created_idx").on(t.createdAt)]);

export const channelConnections = pgTable("channel_connections", {
  id: uuid("id").primaryKey().defaultRandom(),
  provider: text("provider").notNull().default("WHATSAPP"),
  accountLabel: text("account_label").notNull(),
  status: text("status").notNull().default("DISCONNECTED"),
  capabilities: jsonb("capabilities").$type<string[]>().notNull().default(["READ"]),
  ownerUserId: uuid("owner_user_id").references(() => users.id, { onDelete: "set null" }),
  externalAccountId: text("external_account_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index("channel_connections_provider_idx").on(t.provider), index("channel_connections_owner_idx").on(t.ownerUserId)]);

export const conversations = pgTable("conversations", {
  id: uuid("id").primaryKey().defaultRandom(),
  connectionId: uuid("connection_id").notNull().references(() => channelConnections.id, { onDelete: "cascade" }),
  externalId: text("external_id").notNull(),
  leadId: uuid("lead_id").references(() => leads.id, { onDelete: "set null" }),
  contactAddress: text("contact_address").notNull(),
  contactDisplayName: text("contact_display_name"),
  lastMessageAt: timestamp("last_message_at", { withTimezone: true }),
  optOutDetected: boolean("opt_out_detected").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  index("conversations_lead_idx").on(t.leadId),
  index("conversations_connection_idx").on(t.connectionId),
  uniqueIndex("conversations_connection_external_uidx").on(t.connectionId, t.externalId),
  index("conversations_last_message_idx").on(t.lastMessageAt),
]);

export const channelMessages = pgTable("channel_messages", {
  id: uuid("id").primaryKey().defaultRandom(),
  conversationId: uuid("conversation_id").notNull().references(() => conversations.id, { onDelete: "cascade" }),
  externalId: text("external_id").notNull(),
  direction: text("direction").notNull(),
  sentAt: timestamp("sent_at", { withTimezone: true }).notNull(),
  sender: text("sender").notNull(),
  text: text("text"),
  mediaType: text("media_type"),
  deliveryStatus: text("delivery_status"),
  rawMetadata: jsonb("raw_metadata").$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index("channel_messages_conversation_idx").on(t.conversationId), uniqueIndex("channel_messages_conversation_external_uidx").on(t.conversationId, t.externalId), index("channel_messages_sent_idx").on(t.sentAt)]);

export const approvalRequests = pgTable("approval_requests", {
  id: uuid("id").primaryKey().defaultRandom(),
  leadId: uuid("lead_id").references(() => leads.id, { onDelete: "set null" }),
  actionType: text("action_type").$type<ApprovalActionType>().notNull(),
  payload: jsonb("payload").$type<Record<string, unknown>>().notNull().default({}),
  payloadHash: text("payload_hash").notNull(),
  preview: text("preview").notNull(),
  rationale: text("rationale"),
  policyChecks: jsonb("policy_checks").$type<PolicyCheck[]>().notNull().default([]),
  status: text("status").$type<ApprovalStatus>().notNull().default("PENDING"),
  createdByType: text("created_by_type").$type<ActorType>().notNull(),
  createdById: text("created_by_id").notNull(),
  approvedByUserId: uuid("approved_by_user_id").references(() => users.id, { onDelete: "set null" }),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  rejectedByUserId: uuid("rejected_by_user_id").references(() => users.id, { onDelete: "set null" }),
  rejectedAt: timestamp("rejected_at", { withTimezone: true }),
  executedAt: timestamp("executed_at", { withTimezone: true }),
  executionResult: jsonb("execution_result").$type<Record<string, unknown>>().notNull().default({}),
  expiresAt: timestamp("expires_at", { withTimezone: true }),
  version: integer("version").notNull().default(1),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index("approval_requests_status_idx").on(t.status), index("approval_requests_lead_idx").on(t.leadId), index("approval_requests_created_idx").on(t.createdAt)]);

export const qualifications = pgTable("qualifications", {
  id: uuid("id").primaryKey().defaultRandom(),
  leadId: uuid("lead_id").notNull().references(() => leads.id, { onDelete: "cascade" }),
  version: integer("version").notNull().default(1),
  decisionMakers: jsonb("decision_makers").$type<string[]>().notNull().default([]),
  problemStatements: jsonb("problem_statements").$type<string[]>().notNull().default([]),
  desiredOutcome: text("desired_outcome"),
  currentProcess: text("current_process"),
  urgency: text("urgency"),
  explicitBudgetStatement: text("explicit_budget_statement"),
  timeline: text("timeline"),
  constraints: jsonb("constraints").$type<string[]>().notNull().default([]),
  technicalDependencies: jsonb("technical_dependencies").$type<string[]>().notNull().default([]),
  unansweredQuestions: jsonb("unanswered_questions").$type<string[]>().notNull().default([]),
  riskFlags: jsonb("risk_flags").$type<string[]>().notNull().default([]),
  serviceFit: jsonb("service_fit").$type<string[]>().notNull().default([]),
  createdByType: text("created_by_type").$type<ActorType>().notNull(),
  createdById: text("created_by_id").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index("qualifications_lead_idx").on(t.leadId)]);

export const proposals = pgTable("proposals", {
  id: uuid("id").primaryKey().defaultRandom(),
  leadId: uuid("lead_id").notNull().references(() => leads.id, { onDelete: "cascade" }),
  diagnosticId: uuid("diagnostic_id").references(() => diagnostics.id, { onDelete: "set null" }),
  qualificationId: uuid("qualification_id").references(() => qualifications.id, { onDelete: "set null" }),
  version: integer("version").notNull().default(1),
  status: text("status").$type<ProposalStatus>().notNull().default("DRAFT"),
  services: jsonb("services").$type<string[]>().notNull().default([]),
  scope: jsonb("scope").$type<string[]>().notNull().default([]),
  exclusions: jsonb("exclusions").$type<string[]>().notNull().default([]),
  assumptions: jsonb("assumptions").$type<string[]>().notNull().default([]),
  clientDependencies: jsonb("client_dependencies").$type<string[]>().notNull().default([]),
  milestones: jsonb("milestones").$type<Record<string, unknown>[]>().notNull().default([]),
  agencyFeeCents: integer("agency_fee_cents"),
  currency: text("currency").notNull().default("BRL"),
  externalCosts: jsonb("external_costs").$type<Record<string, unknown>[]>().notNull().default([]),
  paymentTerms: text("payment_terms"),
  validityUntil: timestamp("validity_until", { withTimezone: true }),
  renderedContent: text("rendered_content"),
  artifactRef: text("artifact_ref"),
  approvalId: uuid("approval_id").references(() => approvalRequests.id, { onDelete: "set null" }),
  sentAt: timestamp("sent_at", { withTimezone: true }),
  responseNotes: text("response_notes"),
  createdByType: text("created_by_type").$type<ActorType>().notNull(),
  createdById: text("created_by_id").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index("proposals_lead_idx").on(t.leadId), index("proposals_status_idx").on(t.status)]);

export const contracts = pgTable("contracts", {
  id: uuid("id").primaryKey().defaultRandom(),
  leadId: uuid("lead_id").notNull().references(() => leads.id, { onDelete: "cascade" }),
  proposalId: uuid("proposal_id").notNull().references(() => proposals.id, { onDelete: "restrict" }),
  templateId: text("template_id").notNull(),
  templateVersion: text("template_version").notNull(),
  version: integer("version").notNull().default(1),
  status: text("status").$type<ContractStatus>().notNull().default("DRAFT"),
  parties: jsonb("parties").$type<Record<string, unknown>>().notNull().default({}),
  terms: jsonb("terms").$type<Record<string, unknown>>().notNull().default({}),
  responsibilitiesAgency: jsonb("responsibilities_agency").$type<string[]>().notNull().default([]),
  responsibilitiesClient: jsonb("responsibilities_client").$type<string[]>().notNull().default([]),
  paymentObligations: jsonb("payment_obligations").$type<Record<string, unknown>[]>().notNull().default([]),
  deliverables: jsonb("deliverables").$type<string[]>().notNull().default([]),
  supportObligations: jsonb("support_obligations").$type<string[]>().notNull().default([]),
  renderedContent: text("rendered_content"),
  artifactRef: text("artifact_ref"),
  approvalId: uuid("approval_id").references(() => approvalRequests.id, { onDelete: "set null" }),
  signatureProvider: text("signature_provider"),
  externalSignatureId: text("external_signature_id"),
  signedArtifactRef: text("signed_artifact_ref"),
  signedAt: timestamp("signed_at", { withTimezone: true }),
  createdByType: text("created_by_type").$type<ActorType>().notNull(),
  createdById: text("created_by_id").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index("contracts_lead_idx").on(t.leadId), index("contracts_status_idx").on(t.status), index("contracts_proposal_idx").on(t.proposalId)]);

export const clientProjects = pgTable("client_projects", {
  id: uuid("id").primaryKey().defaultRandom(),
  leadId: uuid("lead_id").notNull().references(() => leads.id, { onDelete: "restrict" }),
  contractId: uuid("contract_id").notNull().references(() => contracts.id, { onDelete: "restrict" }),
  name: text("name").notNull(),
  status: text("status").$type<ClientProjectStatus>().notNull().default("PLANNED"),
  ownerUserId: uuid("owner_user_id").references(() => users.id, { onDelete: "set null" }),
  startedAt: timestamp("started_at", { withTimezone: true }),
  targetAt: timestamp("target_at", { withTimezone: true }),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index("client_projects_lead_idx").on(t.leadId), uniqueIndex("client_projects_contract_uidx").on(t.contractId), index("client_projects_status_idx").on(t.status)]);

export const projectObligations = pgTable("project_obligations", {
  id: uuid("id").primaryKey().defaultRandom(),
  projectId: uuid("project_id").notNull().references(() => clientProjects.id, { onDelete: "cascade" }),
  sourceContractId: uuid("source_contract_id").notNull().references(() => contracts.id, { onDelete: "restrict" }),
  party: text("party").notNull(),
  kind: text("kind").notNull(),
  title: text("title").notNull(),
  description: text("description"),
  status: text("status").$type<ObligationStatus>().notNull().default("TODO"),
  dueAt: timestamp("due_at", { withTimezone: true }),
  metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index("project_obligations_project_idx").on(t.projectId), index("project_obligations_status_idx").on(t.status), index("project_obligations_due_idx").on(t.dueAt)]);
