export default {
  testDir: "./tests/e2e",
  testMatch: /.*\.pw\.mjs/,
  timeout: 45_000,
  expect: { timeout: 8_000 },
  fullyParallel: false,
  workers: 1,
  reporter: [["line"]],
  use: {
    baseURL: "http://127.0.0.1:3100",
    browserName: "chromium",
    trace: "retain-on-failure",
    screenshot: "only-on-failure",
  },
  webServer: {
    command: "npm run dev -- -H 127.0.0.1 -p 3100",
    url: "http://127.0.0.1:3100/login",
    reuseExistingServer: false,
    timeout: 120_000,
    env: {
      ...process.env,
      DATA_DRIVER: "mock",
      APP_AUTH_DISABLED: "false",
      SESSION_SECRET: "ci-session-secret-ci-session-secret-123456",
      MCP_AUTH_MODE: "token",
      MCP_API_TOKEN: "ci-mcp-token-ci-mcp-token-123456",
      NEXT_TELEMETRY_DISABLED: "1",
    },
  },
};
