import Link from "next/link";
import { Activity, Bot, CalendarDays, CheckSquare2, KanbanSquare, LayoutDashboard, ListTodo, LogOut, Settings, UserRound, Users } from "lucide-react";
import type { AuthenticatedUser } from "@/lib/auth/types";
import { ThemeToggle } from "./theme-toggle";

const nav=[{href:"/",label:"Overview",icon:LayoutDashboard},{href:"/leads",label:"Leads",icon:Users},{href:"/pipeline",label:"Pipeline",icon:KanbanSquare},{href:"/tasks",label:"Tasks",icon:CheckSquare2},{href:"/calendar",label:"Calendar",icon:CalendarDays},{href:"/actions",label:"Needs Action",icon:ListTodo}];
export function AppShell({children,user}:{children:React.ReactNode;user:AuthenticatedUser}){
 const initials=user.name.split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase();
 return <div className="min-h-screen md:grid md:grid-cols-[220px_1fr]"><aside className="hidden border-r border-default bg-[var(--panel)] md:flex md:h-screen md:sticky md:top-0 md:flex-col"><div className="flex h-14 items-center gap-2 border-b border-default px-4"><div className="grid h-7 w-7 place-items-center rounded-lg bg-[var(--text)] text-[var(--panel)]"><Activity size={15}/></div><span className="font-semibold tracking-tight">AgencyOS</span><span className="text-xs text-muted">Leads</span></div><nav className="flex-1 space-y-1 p-2">{nav.map(({href,label,icon:Icon})=><Link key={href} href={href} className="focus-ring flex items-center gap-2.5 rounded-md px-2.5 py-2 text-sm text-muted hover:bg-[var(--panel-2)] hover:text-[var(--text)]"><Icon size={16}/>{label}</Link>)}</nav><div className="border-t border-default p-2"><Link href="/settings/profile" className="flex items-center gap-2.5 rounded-md px-2.5 py-2 text-sm text-muted hover:bg-[var(--panel-2)] hover:text-[var(--text)]"><UserRound size={16}/>Profile</Link><Link href="/settings/mcp" className="flex items-center gap-2.5 rounded-md px-2.5 py-2 text-sm text-muted hover:bg-[var(--panel-2)] hover:text-[var(--text)]"><Bot size={16}/>ChatGPT</Link>{user.role==="ADMIN"?<><Link href="/settings/team" className="flex items-center gap-2.5 rounded-md px-2.5 py-2 text-sm text-muted hover:bg-[var(--panel-2)] hover:text-[var(--text)]"><Users size={16}/>Team</Link><Link href="/settings" className="flex items-center gap-2.5 rounded-md px-2.5 py-2 text-sm text-muted hover:bg-[var(--panel-2)] hover:text-[var(--text)]"><Settings size={16}/>Settings</Link></>:null}</div><div className="border-t border-default p-3"><div className="flex items-center gap-2"><div className="grid h-8 w-8 place-items-center rounded-full bg-[var(--panel-2)] text-[10px] font-semibold">{initials}</div><div className="min-w-0 flex-1"><div className="truncate text-xs font-medium">{user.name}</div><div className="text-[10px] text-muted">{user.role}</div></div><ThemeToggle/></div><form method="post" action="/api/auth/logout" className="mt-2"><button className="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-xs text-muted hover:bg-[var(--panel-2)] hover:text-[var(--text)]"><LogOut size={13}/>Sign out</button></form></div></aside><div className="min-w-0"><header className="sticky top-0 z-30 flex h-12 items-center justify-between border-b border-default bg-[color:var(--bg)]/90 px-4 backdrop-blur md:hidden"><Link href="/" className="font-semibold">AgencyOS</Link><div className="flex gap-3 text-xs"><Link href="/leads">Leads</Link><Link href="/tasks">Tasks</Link><Link href="/calendar">Calendar</Link></div><div className="flex items-center gap-2"><Link href="/settings/mcp" aria-label="ChatGPT connections" className="text-muted"><Bot size={15}/></Link><Link href="/settings/profile" className="text-xs">{initials}</Link><ThemeToggle/></div></header><main className="mx-auto w-full max-w-[1600px] p-4 md:p-7">{children}</main></div></div>;
}
