import { ProspectingRunForm } from "@/components/prospecting-run-form";
import { requireCurrentUser } from "@/lib/auth/app-auth";
import { listProspectingRuns, SKILL_CATALOG } from "@/lib/services/intelligence";

export default async function ProspectingPage(){
  await requireCurrentUser();const runs=await listProspectingRuns(100);
  return <><header className="mb-6"><h1 className="text-2xl font-semibold tracking-tight">Prospecção com IA</h1><p className="mt-1 text-sm text-muted">Rodadas auditáveis para descoberta → enrichment → diagnóstico → scoring. A pesquisa pública é executada pela skill/agente; o AgencyOS registra o run e seus resultados.</p></header>
  <div className="grid gap-5 xl:grid-cols-[420px_minmax(0,1fr)]"><ProspectingRunForm/><section className="surface-flat rounded-lg p-5"><h2 className="text-sm font-semibold">Rodadas</h2><div className="mt-4 space-y-3">{runs.length?runs.map(run=><article key={run.id} className="rounded-lg border border-default p-4"><div className="flex flex-wrap justify-between gap-2"><div><div className="text-sm font-medium">{run.objective}</div><div className="mt-1 text-xs text-muted">{run.region||"Sem região"} · {run.segments.join(", ")||"segmento aberto"}</div></div><span className="rounded border border-default px-2 py-1 text-[10px]">{run.status}</span></div><div className="mt-3 grid grid-cols-4 gap-2 text-center text-xs"><div><strong>{run.counters.found}</strong><div className="text-[10px] text-muted">encontrados</div></div><div><strong>{run.counters.imported}</strong><div className="text-[10px] text-muted">importados</div></div><div><strong>{run.counters.duplicates}</strong><div className="text-[10px] text-muted">duplicados</div></div><div><strong>{run.counters.rejected}</strong><div className="text-[10px] text-muted">rejeitados</div></div></div></article>):<p className="text-sm text-muted">Nenhuma rodada criada.</p>}</div></section></div>
  <section className="surface-flat mt-5 rounded-lg p-5"><h2 className="text-sm font-semibold">Skills comerciais disponíveis</h2><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{SKILL_CATALOG.map(skill=><div key={skill.id} className="rounded-lg border border-default p-3"><div className="flex justify-between gap-2"><code className="text-xs font-semibold">{skill.id}@{skill.version}</code><span className="text-[10px] text-muted">{skill.autonomy}</span></div><p className="mt-2 text-xs leading-5 text-muted">{skill.description}</p></div>)}</div></section></>;
}
