import Link from "next/link";
import { ChannelConnectionForm } from "@/components/channel-connection-form";
import { requireCurrentUser } from "@/lib/auth/app-auth";
import { listChannelConnections, listConversations } from "@/lib/services/communications";

export default async function ConversationsPage(){
  await requireCurrentUser();const[connections,conversations]=await Promise.all([listChannelConnections(),listConversations({limit:200})]);
  return <><header className="mb-6"><h1 className="text-2xl font-semibold tracking-tight">WhatsApp & conversas</h1><p className="mt-1 text-sm text-muted">Sincronização read-only para análise por IA. Não existe envio bruto por agente; mensagens externas passam pela central de aprovações.</p></header>
  <div className="grid gap-5 xl:grid-cols-[380px_minmax(0,1fr)]"><div className="space-y-4"><ChannelConnectionForm/><section className="surface-flat rounded-lg p-5"><h2 className="text-sm font-semibold">Conexões</h2><div className="mt-3 space-y-2">{connections.length?connections.map(c=><div key={c.id} className="rounded-lg border border-default p-3"><div className="flex justify-between gap-2 text-xs"><strong>{c.accountLabel}</strong><span>{c.status}</span></div><div className="mt-1 text-[10px] text-muted">{c.provider} · {c.capabilities.join(", ")}</div><code className="mt-2 block truncate text-[10px] text-muted">{c.id}</code></div>):<p className="text-xs text-muted">Nenhuma conexão registrada.</p>}</div></section></div>
  <section className="surface-flat rounded-lg p-5"><h2 className="text-sm font-semibold">Conversas sincronizadas</h2><div className="mt-4 space-y-2">{conversations.length?conversations.map(c=><article key={c.id} className="rounded-lg border border-default p-4"><div className="flex flex-wrap justify-between gap-2"><div><div className="text-sm font-medium">{c.contactDisplayName??c.contactAddress}</div><div className="text-xs text-muted">{c.contactAddress}</div></div><div className="flex gap-2">{c.optOutDetected?<span className="rounded bg-red-50 px-2 py-1 text-[10px] text-red-700 dark:bg-red-950 dark:text-red-300">OPT-OUT</span>:null}{c.leadId?<Link className="rounded border border-default px-2 py-1 text-[10px]" href={"/leads/"+c.leadId}>Abrir lead</Link>:<span className="rounded border border-default px-2 py-1 text-[10px] text-muted">não vinculado</span>}</div></div><div className="mt-2 text-[10px] text-muted">{c.lastMessageAt?new Date(c.lastMessageAt).toLocaleString("pt-BR"):"Sem mensagens"}</div></article>):<p className="text-sm text-muted">Nenhuma conversa foi sincronizada ainda.</p>}</div></section></div></>;
}
